# -*- coding: utf-8 -*-
"""Exp 11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kBqVoK84sSkZvZHGuBqIXhld5MT36MGx
"""

import pandas as pd
df = pd.read_csv("titanic.csv")

#1
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

df.head()

#2
df['Fare'] = (df['Fare'] - df['Fare'].min()) / (df['Fare'].max() - df['Fare'].min())
df.head()

#3
df['is_minor'] = df['Age'].apply(lambda x: 1 if x < 18 else 0)

df.head()







import pandas as pd
df = pd.read_csv("Iris.csv")

#4
df = df.fillna(df.median(numeric_only=True))
df.head()

#5
df = pd.get_dummies(df, columns=['Species'])
df.head()

#6
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df['SepalLengthCm'] = scaler.fit_transform(df[['SepalLengthCm']])
df.head()



import pandas as pd
df = pd.read_csv("boston.csv")

df.head()

#7
df = df.dropna(subset=['chas'])
df.head()

#8
Q1 = df['tax'].quantile(0.25)
Q3 = df['tax'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df['tax'] >= lower) & (df['tax'] <= upper)]

#9
df['dis'].fillna(df['dis'].median(), inplace=True)
df.head()

import pandas as pd
df = pd.read_csv("winequality-red.csv")
df.head()

#10

df = df.drop_duplicates()
df.head()

#11
df['citric acid'].fillna(df['citric acid'].mean(), inplace=True)
df.head()

#12
from scipy import stats

df = df[(abs(stats.zscore(df['pH'])) < 3)]
df.head()